grails-app/domain/videorentalsystem/ChildrenVideo.groovy
package videorentalsystem

class ChildrenVideo extends Video {

	Integer maximumAge
	
	//Video video
	
	//static belongsTo = [video : Video]
	
    static constraints = {
		
		maximumAge (min:1, max:120)
		// maximumAge (range: 1..120)
		
    }
	
	String toString()
	{
		"Children Video + ${maximumAge}"
	}
}

grails-app/domain/videorentalsystem/NewRelease.groovy
package videorentalsystem

class NewRelease extends Video {

	Date yearReleased
	
	//Video video
	
	//static belongsTo = [video : Video]
	
    static constraints = {
		
		yearReleased(max: new Date())
    }
	
	String toString()
	{
		"New Release + ${yearReleased}"
	}
}

grails-app/domain/videorentalsystem/Regular.groovy
package videorentalsystem


class Regular extends Video {

	//Video video
	
	//static belongsTo = [video : Video]
	
	String toString()
	{
		"Regular"
	}
	
    static constraints = {
    }
}

grails-app/domain/videorentalsystem/User.groovy
package videorentalsystem

class User {
	
	String fullName
	
	String userName
	
	String password

    static constraints = {
		
		fullName()
		
		userName(unique : true, blank : false)
		
		password(password : true)
		
    }
}

grails-app/domain/videorentalsystem/Video.groovy
package videorentalsystem

import abstractDomains.VideoGenre;
import abstractDomains.VideoType;

class Video {
	
	String videoTitle
	
	VideoType videoType
	
	VideoGenre videoGenre
	
	//static hasOne = [newReleases : NewRelease, regular : Regular]
	
	String toString()
	{
		"${videoTitle}"
	}
	
	static constraints = {
		
		videoTitle (blank: false, unique: true)
			
		//videoType(inList:["Children's Video", "Regular", "New Release"])
		
		//videoGenre(inList:["Action", "Comedy", "Adventure", "Drama"])
	}
	
//	static mapping = {
//		
//		tablePerHierarchy false
//		
//	}
	
}

grails-app/domain/videorentalsystem/VideoGenre.groovy
package videorentalsystem

class VideoGenre {

	//String videoGenre
	
//	String toString()
//	{
//		"${videoGenre}"
//	}
//	
	//static belongsTo = [video : Video]
	
    static constraints = {
		
		videoGenre(inList: ["Action", "Comedy", "Romance", "Animation"])
		
    }
}

grails-app/domain/videorentalsystem/VideoType.groovy
package videorentalsystem

class VideoType {
	
//	String videoType
//	
//	String toString()
//	{
//		"${videoType}"
//	}
//	
    static constraints = {
	
		videoType(inList:["Children's Video", "Regular", "New Release"])
		
    }
}

grails-app/controllers/videorentalsystem/ChildrenVideoController.groovy
package videorentalsystem

class ChildrenVideoController {
	
	def beforeInterceptor = [action:this.&auth]
	
	def scaffold=true
	
	def index() {
		redirect(action: "list") 
	}
	
	def auth() {
		if(!session.user) {
			redirect(controller:"User", action:"login")
			return false
		}
	}
}

grails-app/controllers/videorentalsystem/NewReleaseController.groovy
package videorentalsystem

class NewReleaseController {

	def beforeInterceptor = [action:this.&auth]
	
	def scaffold=true
	
	def index() {
		redirect(action: "list")
	}
	
	def auth() {
		if(!session.user) {
			redirect(controller:"User", action:"login")
			return false
		}
	}
}

grails-app/controllers/videorentalsystem/RegularController.groovy
package videorentalsystem

class RegularController {

   def beforeInterceptor = [action:this.&auth]
	
	def scaffold=true
	
	def index() {
		redirect(action: "list")
	}
	
	def auth() {
		if(!session.user) {
			redirect(controller:"User", action:"login")
			return false
		}
	}
}

grails-app/controllers/videorentalsystem/UserController.groovy
package videorentalsystem

import org.springframework.dao.DataIntegrityViolationException

class UserController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index() {
        redirect(action: "login", params: params)
    }
	
	def login = {}
	
	def authenticate = {
		def user = User.findByUserNameAndPassword(params.userName, params.password)
		if(user){
			session.user = user
			flash.message = "Hello ${user.fullName}!"
			redirect(action:"login")
			
		}else{
		flash.message = "Sorry, ${params.userName}. Please try again."
		redirect(action:"login")
		}
	}
	
	def logout = {
		flash.message = "Goodbye ${session.user.fullName}"
		session.user = null
		redirect(action:"login")
	}
	
    def list(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        [userInstanceList: User.list(params), userInstanceTotal: User.count()]
    }

    def create() {
        [userInstance: new User(params)]
    }

    def save() {
        def userInstance = new User(params)
        if (!userInstance.save(flush: true)) {
            render(view: "create", model: [userInstance: userInstance])
            return
        }

        flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), userInstance.id])
        redirect(action: "show", id: userInstance.id)
    }

    def show(Long id) {
        def userInstance = User.get(id)
        if (!userInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), id])
            redirect(action: "list")
            return
        }

        [userInstance: userInstance]
    }

    def edit(Long id) {
        def userInstance = User.get(id)
        if (!userInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), id])
            redirect(action: "list")
            return
        }

        [userInstance: userInstance]
    }

    def update(Long id, Long version) {
        def userInstance = User.get(id)
        if (!userInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), id])
            redirect(action: "list")
            return
        }

        if (version != null) {
            if (userInstance.version > version) {
                userInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                          [message(code: 'user.label', default: 'User')] as Object[],
                          "Another user has updated this User while you were editing")
                render(view: "edit", model: [userInstance: userInstance])
                return
            }
        }

        userInstance.properties = params

        if (!userInstance.save(flush: true)) {
            render(view: "edit", model: [userInstance: userInstance])
            return
        }

        flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label', default: 'User'), userInstance.id])
        redirect(action: "show", id: userInstance.id)
    }

    def delete(Long id) {
        def userInstance = User.get(id)
        if (!userInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), id])
            redirect(action: "list")
            return
        }

        try {
            userInstance.delete(flush: true)
            flash.message = message(code: 'default.deleted.message', args: [message(code: 'user.label', default: 'User'), id])
            redirect(action: "list")
        }
        catch (DataIntegrityViolationException e) {
            flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'user.label', default: 'User'), id])
            redirect(action: "show", id: id)
        }
    }
}

grails-app/controllers/videorentalsystem/VideoController.groovy
package videorentalsystem

class VideoController {
    
	def calculatePriceService
	
	def beforeInterceptor = [action:this.&auth]
	
	def scaffold = true
	
	def index()
	{
		redirect(action: "list")
	}
	
	def auth() {
		if(!session.user) {
			redirect(controller:"User", action:"login")
			return false
		}
	}
	
	def calcPrice()
	{
		def totalPriceInstance
		def tp = 222
		
		totalPriceInstance = calculatePriceService.calcPrice(2, 1)
	}
}

grails-app/controllers/videorentalsystem/VideoGenreController.groovy
package videorentalsystem

class VideoGenreController {

	def scaffold = true
	
	def index()
	{
		redirect(action: list)
	}
}

grails-app/controllers/videorentalsystem/VideoTypeController.groovy
package videorentalsystem

class VideoTypeController {
	
	def scaffold = true
	
    def index()
	{
		redirect(action: list)
	}
}

grails-app/views/childrenVideo/_form.gsp
<%@ page import="videorentalsystem.ChildrenVideo" %>



<div class="fieldcontain ${hasErrors(bean: childrenVideoInstance, field: 'videoTitle', 'error')} required">
	<label for="videoTitle">
		<g:message code="childrenVideo.videoTitle.label" default="Video Title" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="videoTitle" required="" value="${childrenVideoInstance?.videoTitle}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: childrenVideoInstance, field: 'maximumAge', 'error')} required">
	<label for="maximumAge">
		<g:message code="childrenVideo.maximumAge.label" default="Maximum Age" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="maximumAge" type="number" min="1" max="120" value="${childrenVideoInstance.maximumAge}" required=""/>
</div>

<div class="fieldcontain ${hasErrors(bean: childrenVideoInstance, field: 'videoGenre', 'error')} required">
	<label for="videoGenre">
		<g:message code="childrenVideo.videoGenre.label" default="Video Genre" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="videoGenre" from="${abstractDomains.VideoGenre?.values()}" keys="${abstractDomains.VideoGenre.values()*.name()}" required="" value="${childrenVideoInstance?.videoGenre?.name()}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: childrenVideoInstance, field: 'videoType', 'error')} required">
	<label for="videoType">
		<g:message code="childrenVideo.videoType.label" default="Video Type" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="videoType" from="${abstractDomains.VideoType?.values()}" keys="${abstractDomains.VideoType.values()*.name()}" required="" value="${childrenVideoInstance?.videoType?.name()}"/>
</div>

grails-app/views/childrenVideo/create.gsp
<%@ page import="videorentalsystem.ChildrenVideo" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'childrenVideo.label', default: 'ChildrenVideo')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-childrenVideo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-childrenVideo" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${childrenVideoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${childrenVideoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form action="save" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/childrenVideo/edit.gsp
<%@ page import="videorentalsystem.ChildrenVideo" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'childrenVideo.label', default: 'ChildrenVideo')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-childrenVideo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-childrenVideo" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${childrenVideoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${childrenVideoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form method="post" >
				<g:hiddenField name="id" value="${childrenVideoInstance?.id}" />
				<g:hiddenField name="version" value="${childrenVideoInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate="" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/childrenVideo/list.gsp
<%@ page import="videorentalsystem.ChildrenVideo" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'childrenVideo.label', default: 'ChildrenVideo')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-childrenVideo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-childrenVideo" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
					
						<g:sortableColumn property="videoTitle" title="${message(code: 'childrenVideo.videoTitle.label', default: 'Video Title')}" />
					
						<g:sortableColumn property="maximumAge" title="${message(code: 'childrenVideo.maximumAge.label', default: 'Maximum Age')}" />
					
						<g:sortableColumn property="videoGenre" title="${message(code: 'childrenVideo.videoGenre.label', default: 'Video Genre')}" />
					
						<g:sortableColumn property="videoType" title="${message(code: 'childrenVideo.videoType.label', default: 'Video Type')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${childrenVideoInstanceList}" status="i" var="childrenVideoInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${childrenVideoInstance.id}">${fieldValue(bean: childrenVideoInstance, field: "videoTitle")}</g:link></td>
					
						<td>${fieldValue(bean: childrenVideoInstance, field: "maximumAge")}</td>
					
						<td>${fieldValue(bean: childrenVideoInstance, field: "videoGenre")}</td>
					
						<td>${fieldValue(bean: childrenVideoInstance, field: "videoType")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${childrenVideoInstanceTotal}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/childrenVideo/show.gsp
<%@ page import="videorentalsystem.ChildrenVideo" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'childrenVideo.label', default: 'ChildrenVideo')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-childrenVideo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-childrenVideo" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list childrenVideo">
			
				<g:if test="${childrenVideoInstance?.videoTitle}">
				<li class="fieldcontain">
					<span id="videoTitle-label" class="property-label"><g:message code="childrenVideo.videoTitle.label" default="Video Title" /></span>
					
						<span class="property-value" aria-labelledby="videoTitle-label"><g:fieldValue bean="${childrenVideoInstance}" field="videoTitle"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${childrenVideoInstance?.maximumAge}">
				<li class="fieldcontain">
					<span id="maximumAge-label" class="property-label"><g:message code="childrenVideo.maximumAge.label" default="Maximum Age" /></span>
					
						<span class="property-value" aria-labelledby="maximumAge-label"><g:fieldValue bean="${childrenVideoInstance}" field="maximumAge"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${childrenVideoInstance?.videoGenre}">
				<li class="fieldcontain">
					<span id="videoGenre-label" class="property-label"><g:message code="childrenVideo.videoGenre.label" default="Video Genre" /></span>
					
						<span class="property-value" aria-labelledby="videoGenre-label"><g:fieldValue bean="${childrenVideoInstance}" field="videoGenre"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${childrenVideoInstance?.videoType}">
				<li class="fieldcontain">
					<span id="videoType-label" class="property-label"><g:message code="childrenVideo.videoType.label" default="Video Type" /></span>
					
						<span class="property-value" aria-labelledby="videoType-label"><g:fieldValue bean="${childrenVideoInstance}" field="videoType"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form>
				<fieldset class="buttons">
					<g:hiddenField name="id" value="${childrenVideoInstance?.id}" />
					<g:link class="edit" action="edit" id="${childrenVideoInstance?.id}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/newRelease/list.gsp
<%@ page import="videorentalsystem.NewRelease" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'newRelease.label', default: 'NewRelease')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-newRelease" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-newRelease" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
					
						<g:sortableColumn property="videoTitle" title="${message(code: 'newRelease.videoTitle.label', default: 'Video Title')}" />
					
						<g:sortableColumn property="yearReleased" title="${message(code: 'newRelease.yearReleased.label', default: 'Year Released')}" />
					
						<g:sortableColumn property="videoGenre" title="${message(code: 'newRelease.videoGenre.label', default: 'Video Genre')}" />
					
						<g:sortableColumn property="videoType" title="${message(code: 'newRelease.videoType.label', default: 'Video Type')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${newReleaseInstanceList}" status="i" var="newReleaseInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${newReleaseInstance.id}">${fieldValue(bean: newReleaseInstance, field: "videoTitle")}</g:link></td>
					
						<td><g:formatDate date="${newReleaseInstance.yearReleased}" /></td>
					
						<td>${fieldValue(bean: newReleaseInstance, field: "videoGenre")}</td>
					
						<td>${fieldValue(bean: newReleaseInstance, field: "videoType")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${newReleaseInstanceTotal}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/regular/list.gsp
<%@ page import="videorentalsystem.Regular" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'regular.label', default: 'Regular')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-regular" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-regular" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
					
						<g:sortableColumn property="videoTitle" title="${message(code: 'regular.videoTitle.label', default: 'Video Title')}" />
					
						<g:sortableColumn property="videoGenre" title="${message(code: 'regular.videoGenre.label', default: 'Video Genre')}" />
					
						<g:sortableColumn property="videoType" title="${message(code: 'regular.videoType.label', default: 'Video Type')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${regularInstanceList}" status="i" var="regularInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${regularInstance.id}">${fieldValue(bean: regularInstance, field: "videoTitle")}</g:link></td>
					
						<td>${fieldValue(bean: regularInstance, field: "videoGenre")}</td>
					
						<td>${fieldValue(bean: regularInstance, field: "videoType")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${regularInstanceTotal}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/video/calcPrice.gsp
<%@ page import="videorentalsystem.Video" %>
<!DOCTYPE html>
<html>
	<head>
		
	</head>
	<body>
		"totalPriceInstance "	totalPriceInstance
		${totalPriceInstance}
		
		${tp}
	</body>
</html>

grails-app/views/video/list.gsp
<%@ page import="videorentalsystem.Video" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'video.label', default: 'Video')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
		
		<script type="text/javascript">
	
  			function enableText(checkBool, textId)
  			{
			    textFldObj = document.getElementById(textId);
	    		//Disable the text field
	    		textFldObj.disabled = !checkBool;
	    		//Clear value in the text field
	    		if (!checkBool) { textFldObj.value = ''; }
  			}

		</script>
		
	</head>
	<body>
		<a href="#list-video" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
			</ul>
		</div>
		<div id="list-video" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
						
						<g:sortableColumn property="videoId" title="${message(code: 'video.id.label', default: 'Id')}" />
					
						<g:sortableColumn property="videoTitle" title="${message(code: 'video.videoTitle.label', default: 'Video Title')}" />
					
						<g:sortableColumn property="videoGenre" title="${message(code: 'video.videoGenre.label', default: 'Video Genre')}" />
					
						<g:sortableColumn property="videoType" title="${message(code: 'video.videoType.label', default: 'Video Type')}" />
					
						<g:sortableColumn property="numberOfDays" title="${message(code: 'video.numberOfDays.label', default: 'Number of Days')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${videoInstanceList}" status="i" var="videoInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:checkBox checked="false" name="allVideos" value="${videoInstance.id}" onclick="enableText(this.checked, '${videoInstance.id}');" /></td>
						
						<td><g:link action="show" id="${videoInstance.id}">${fieldValue(bean: videoInstance, field: "videoTitle")}</g:link></td>
					
						<td>${fieldValue(bean: videoInstance, field: "videoGenre")}</td>
					
						<td>${fieldValue(bean: videoInstance, field: "videoType")}</td>
						
						<td><g:textField id="${videoInstance.id}" name="numberOfDays" disabled="true" /> </td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			
			<g:form>
				<fieldset class="buttons">
					<g:hiddenField name="id" value="${userInstance?.id}" />
					<g:link class="calcPrice" action="calcPrice" id="${userInstance?.id}"><g:message code="default.button.calcPrice.label" default="Calculate Rent Price" /></g:link>
				</fieldset>
			</g:form>
			
			<div class="pagination">
				<g:paginate total="${videoInstanceTotal}" />
			</div>
		</div>
	</body>
</html>